# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    assets:
        version: '%env(APP_VERSION)%'
        packages:
            css:
                base_path: '/assets/css'
            bootstrap:
                base_path: '/assets/bootstrap-5.3.3-dist'
            bootstrap-icon:
                base_path: '/assets/bootstrap-icons-1.11.3'
            jquery:
                base_path: '/assets/jquery'
                
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
