framework:
    messenger:
#        failure_transport: failed

        transports:
#            async:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                retry_strategy:
#                    max_retries: 3
#                    multiplier: 2
#            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            App\Message\BolaoResultadoNotificarMessage: sync
            
when@dev:
    framework:
      messenger:
          transports:
              sync: 'sync://'
          routing:
              Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
