FROM php:fpm

RUN apt update -y

RUN apt install -y libicu-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev

RUN pecl install redis

RUN docker-php-ext-enable redis

RUN docker-php-ext-install intl

RUN docker-php-ext-install pdo

RUN docker-php-ext-install pdo_mysql

RUN docker-php-ext-install gd

RUN docker-php-ext-install mbstring

WORKDIR /app