-- MySQL Script generated by MySQL Workbench
-- Thu Sep 19 10:58:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loteria` DEFAULT CHARACTER SET utf8 ;
USE `loteria` ;

-- -----------------------------------------------------
-- Table `loteria`.`loteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`loteria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `uuid` BINARY(16) NOT NULL,
  `api_url` VARCHAR(255) NOT NULL,
  `slug_url` VARCHAR(255) NOT NULL,
  `aposta` JSON NOT NULL,
  `dezenas` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `slug_url_UNIQUE` (`slug_url` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`concurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`concurso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loteria_id` INT NOT NULL,
  `numero` INT NOT NULL,
  `apuracao` DATE NULL,
  `municipio` VARCHAR(60) NULL,
  `local` VARCHAR(60) NULL,
  `uf` VARCHAR(2) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `uuid` BINARY(16) NOT NULL,
  `rateio_premio` JSON NULL,
  `dezenas` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_concurso_loteria_idx` (`loteria_id` ASC) VISIBLE,
  CONSTRAINT `fk_concurso_loteria`
    FOREIGN KEY (`loteria_id`)
    REFERENCES `loteria`.`loteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `roles` LONGTEXT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `last_access` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`arquivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `nome_original` VARCHAR(255) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `arquivo_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`bolao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`bolao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `concurso_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `usuario_id` INT NOT NULL,
  `cota_valor` DECIMAL(10,2) UNSIGNED NULL,
  `planilha_jogos_csv` INT NULL,
  `comprovante_jogos_pdf` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bolao_concurso_idx` (`concurso_id` ASC) VISIBLE,
  INDEX `fk_bolao_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_bolao_arquivo_planilha_jogos_csv_idx` (`planilha_jogos_csv` ASC) VISIBLE,
  INDEX `fk_bolao_arquivo_comprovante_jogos_pdf_idx` (`comprovante_jogos_pdf` ASC) INVISIBLE,
  CONSTRAINT `fk_bolao_concurso`
    FOREIGN KEY (`concurso_id`)
    REFERENCES `loteria`.`concurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bolao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `loteria`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bolao_arquivo1`
    FOREIGN KEY (`planilha_jogos_csv`)
    REFERENCES `loteria`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bolao_arquivo2`
    FOREIGN KEY (`comprovante_jogos_pdf`)
    REFERENCES `loteria`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`aposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`aposta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `bolao_id` INT NOT NULL,
  `dezenas` JSON NOT NULL,
  `conferida` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `quantidade_acertos` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aposta_bolao_idx` (`bolao_id` ASC) INVISIBLE,
  CONSTRAINT `fk_aposta_bolao`
    FOREIGN KEY (`bolao_id`)
    REFERENCES `loteria`.`bolao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`rememberme_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`rememberme_token` (
  `series` VARCHAR(88) NOT NULL,
  `value` VARCHAR(88) NOT NULL,
  `lastUsed` DATETIME NOT NULL,
  `class` VARCHAR(100) NOT NULL,
  `username` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`reset_password_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`reset_password_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `selector` VARCHAR(20) NOT NULL,
  `hashed_token` VARCHAR(100) NOT NULL,
  `requested_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_INDEX` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reset_password_request_usuario`
    FOREIGN KEY (`user_id`)
    REFERENCES `loteria`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`apostador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`apostador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `email` VARCHAR(180) NULL,
  `nome` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `bolao_id` INT NOT NULL,
  `cota_paga` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `cota_quantidade` INT(4) UNSIGNED NOT NULL DEFAULT 1,
  `arquivo_id` INT NOT NULL,
  `pix` VARCHAR(180) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apostador_bolao_idx` (`bolao_id` ASC) VISIBLE,
  INDEX `fk_apostador_arquivo_idx` (`arquivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_apostador_bolao`
    FOREIGN KEY (`bolao_id`)
    REFERENCES `loteria`.`bolao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apostador_arquivo`
    FOREIGN KEY (`arquivo_id`)
    REFERENCES `loteria`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
