-- MySQL Script generated by MySQL Workbench
-- Wed Jul 24 11:50:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loteria` DEFAULT CHARACTER SET utf8 ;
USE `loteria` ;

-- -----------------------------------------------------
-- Table `loteria`.`loteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`loteria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `uuid` BINARY(16) NOT NULL,
  `api_url` VARCHAR(255) NOT NULL,
  `slug_url` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `slug_url_UNIQUE` (`slug_url` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`concurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`concurso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loteria_id` INT NOT NULL,
  `numero` INT NOT NULL,
  `apuracao` DATE NULL,
  `municipio` VARCHAR(60) NULL,
  `local` VARCHAR(60) NULL,
  `uf` VARCHAR(2) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `uuid` BINARY(16) NOT NULL,
  `rateio_premio` JSON NULL,
  `dezenas` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_concurso_loteria_idx` (`loteria_id` ASC),
  CONSTRAINT `fk_concurso_loteria`
    FOREIGN KEY (`loteria_id`)
    REFERENCES `loteria`.`loteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`arquivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `nome_original` VARCHAR(255) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `arquivo_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`bolao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`bolao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `concurso_id` INT NOT NULL,
  `arquivo_comprovante_pdf_id` INT NULL,
  `arquivo_planilha_csv_id` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bolao_concurso_idx` (`concurso_id` ASC),
  INDEX `fk_bolao_arquivo_comprovante_pdf_idx` (`arquivo_comprovante_pdf_id` ASC),
  INDEX `fk_bolao_arquivo_planilha_csv_idx` (`arquivo_planilha_csv_id` ASC),
  CONSTRAINT `fk_bolao_concurso`
    FOREIGN KEY (`concurso_id`)
    REFERENCES `loteria`.`concurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bolao_arquivo_compovante_pdf`
    FOREIGN KEY (`arquivo_comprovante_pdf_id`)
    REFERENCES `loteria`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bolao_arquivo_planilha_csv`
    FOREIGN KEY (`arquivo_planilha_csv_id`)
    REFERENCES `loteria`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`aposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`aposta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `bolao_id` INT NOT NULL,
  `dezenas` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aposta_bolao_idx` (`bolao_id` ASC),
  CONSTRAINT `fk_aposta_bolao`
    FOREIGN KEY (`bolao_id`)
    REFERENCES `loteria`.`bolao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
